version: '3'
services:
    transfer:
        build: ./DataTransfer
        ports:
            - "2020:2020"
        volumes:
             - ./DataTransfer:/src
        environment:
            PORT: 2020
    historical:
        build: ./HistoricalAccess
        ports:
            - "400:400"
        volumes:
             - share-vol:/historical
        environment:
            PORT: 400
    telemetry:
        build: ./TelemetryWeb
        ports:
            - "3000:3000"
        working_dir: /TelemetryWeb/TelemetryWeb
        volumes:
             - .:/TelemetryWeb
        environment:
            PORT: 4000
        depends_on:
            - transfer
            - historical
    ingestion:
        build: ./Ingestion
        ports:
            - "800:800"
        volumes:
             - share-vol:/ingestion
        depends_on:
            - transfer
            
volumes:
    share-vol: