version: '3'
services:
    transfer:
        build: ./DataTransfer
        ports:
            - "2020:2020"
        volumes:
             - ./DataTransfer:/src
        environment:
            PORT: 2020
        networks:
            - backend
    #historical:
    #    build: ./HistoricalAccess
    #    ports:
    #        - "400:400"
    #    volumes:
    #         - ./HistoricalAccess:/src
    #    environment:
    #        PORT: 400
    #    networks:
    #        - backend
    telemetry:
        build: ./TelemetryWeb
        container_name: telemetry
        ports:
            - "3000:3000"
        volumes:
             - ./TelemetryWeb:/src
        environment:
            PORT: 3000
        depends_on:
            - transfer
    #        - historical
        networks:
            - backend
    ingestion:
        build: ./Ingestion
        ports:
            - "800:800"
        volumes:
             - ./Ingestion:/src
        depends_on:
            - transfer
        networks:
            - backend
networks:
    backend:
        driver: "bridge"