version: '3'
services:
    transfer:
        build: ./DataTransfer
        ports:
            - "2020:2020"
        volumes:
             - ./DataTransfer:/src
        environment:
            PORT: 2020
    historical:
        build: ./HistoricalAccess
        ports:
            - "400:400"
        volumes:
             - ./HistoricalAccess:/src
        environment:
            PORT: 400
    telemetry:
        build: ./TelemetryWeb
        ports:
            - "3000:3000"
        volumes:
             - ./TelemetryWeb:/src
        environment:
            PORT: 4000
        depends_on:
            - transfer
            - historical
        links:
            - transfer
    ingestion:
        build: ./Ingestion
        ports:
            - "800:800"
        volumes:
             - ./Ingestion:/src
        depends_on:
            - transfer
        links:
            - transfer