version: '2'
services:
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
    node:
        build: ./node
        ports:
            - "4000:4000"
            - "3030:3030"
        volumes:
             - .:/usr/src/app
        environment:
            PORT: 4000
            REDIS_PORT: 6379
            WEB_SOCKET_PORT: 3030
        depends_on:
            - redis
    python:
        build: ./python
        ports:
            - "800:800"
        volumes:
             - .:/usr/src/app
        depends_on:
            - redis
            - node